stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/khoty-wolie/house-price-api"
  DOCKER_HOST: "tcp://docker:2375"  # Ajout du bon host Docker

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker pull $IMAGE_NAME
    - docker run -d -p 8000:8000 $IMAGE_NAME
