image: docker:latest  # Utilisation de Docker officiel

services:
  - docker:dind  # Activation du service Docker in Docker

variables:
  DOCKER_HOST: tcp://docker:2375  # Indique le bon host Docker
  DOCKER_TLS_CERTDIR: ""  # Désactiver le TLS pour Docker in Docker
  IMAGE_NAME: "registry.gitlab.com/khoty-wolie/house-price-api"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker pull $IMAGE_NAME
    - docker run -d -p 8000:8000 $IMAGE_NAME
